CREATE DATABASE `usales_dev`;
CREATE USER 'usales_user'@'localhost' IDENTIFIED BY 'Welcome1';
GRANT CREATE ROUTINE, CREATE VIEW, ALTER, SHOW VIEW, CREATE, ALTER ROUTINE, EVENT, INSERT, SELECT, DELETE, TRIGGER, GRANT OPTION, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES, INDEX ON `usales\_dev`.* TO 'usales_user'@'localhost';
FLUSH PRIVILEGES;
